### ISSUE TITLE
【计算】在分辩率为1024*768 下，云主机绑定公网IP后解绑公网IP，提示按钮不可点击

### ISSUE THREAD

**Issue by landhu** [icaoda/wscloud-ui-issure-tracking#25]
Traceback (most recent call last):
  File "c:\python27\Lib\unittest\case.py", line 329, in run
    testMethod()
  File "c:\test\workspace\test_compute\testcase\compute\server_base.py", line 436, in test_bind_unbind_floatingip
    self.server.unbind_fip(fip)
  File "c:\test\workspace\test_compute\resource\compute\server.py", line 582, in unbind_fip
    name=self.name, fip=fip.get_ip())
  File "c:\test\workspace\test_compute\page\compute\server\server_page.py", line 963, in unbind_floating_ip
    row.do_more_action_action(act=u"公网IP", act1=u"解绑")
  File "c:\test\workspace\test_compute\page\compute\server\server_page.py", line 107, in do_more_action_action
    self.more_action_action(text=act, text1=act1)
  File "c:\test\workspace\test_compute\common\element.py", line 813, in more_action_action
    self.driver.click(more2.ele)
  File "c:\test\workspace\test_compute\common\action.py", line 337, in click
    ele.click()
  File "c:\test\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\test\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "c:\test\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "c:\test\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.1.7600 x86_64)

URL  http://10.3.207.228:8080/job/test_compute/208/allure/#suites/459c86269815a6ee629fd3ad6f37615d/e3b247fdc9270c65/

**Comment by icaoda** [comment]
切换到ubuntu无头模式运行，虚拟显示器窗口设置为1280x1024解决问题。
